// Auto-generated by gitrev.cmd - DO NOT EDIT
#ifndef BUILDNUMBER_H
#define BUILDNUMBER_H

#define BUILD_NUMBER 6
#define BUILD_NUMBER_STR "6"
#define COMMIT_HASH "a5fb860"
#define BUILD_TIME_UTC "2026-01-20 09:20:05 UTC"
#define BUILD_HOST "DESKTOP-TJLN3B8"

#endif // BUILDNUMBER_H
